{% set name = "aws-cdk.aws-autoscaling-common" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.aws-autoscaling-common-{{ version }}.tar.gz
  sha256: a4b4f6346e99514a56a7003c083e9d54c029ca1f86303df46caf7c4bfa07719e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.aws-iam ==1.204.0
    - aws-cdk.core ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.aws_autoscaling_common
    - aws_cdk.aws_autoscaling_common._jsii
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-cdk
  summary: Common implementation package for @aws-cdk/aws-autoscaling and @aws-cdk/aws-applicationautoscaling
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
